# Generated by Django 3.0.3 on 2020-05-29 15:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('project', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='green', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('dataframe', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('project_total', models.DurationField(blank=True, null=True)),
                ('project_avg', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('custom_duration', models.DurationField(blank=True, null=True)),
                ('daily_avg', models.CharField(blank=True, default='0:00:00', max_length=100, null=True)),
                ('total', models.CharField(blank=True, default='0:00:00', max_length=100, null=True)),
                ('display_avg', models.CharField(blank=True, max_length=100, null=True)),
                ('display_total', models.CharField(blank=True, max_length=100, null=True)),
                ('dataframe', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasktracker.ProjectModel')),
            ],
        ),
    ]
